# https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md#configuration-file

version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
flags:
  - -trimpath
  - -tags=netgo
goos:
  - linux
goarch:
  - amd64
  - arm64
binary: rapidblock-{{ .Os }}-{{ .Arch }}
ldflags:
  - "-X main.Version={{ .Version }}"
